package api

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/singhand-labs/AegisCrawler/internal/llm/budget"
	"github.com/singhand-labs/AegisCrawler/internal/llm/intent"
	platformrecording "github.com/singhand-labs/AegisCrawler/internal/recording"
	"go.uber.org/zap"
)

type intentPredictor interface {
	Predict(ctx context.Context, recording map[string]any) (*intent.PredictionResult, error)
}

// PredictIntent godoc
// @Summary Predict user intent from recording
// @Description Takes a PageAgent recording and returns candidate intents generated by LLM.
// @Tags admin
// @Accept json
// @Produce json
// @Security AdminApiKey
// @Param request body PredictIntentRequest true "Recording"
// @Success 200 {object} PredictIntentResponse
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 429 {object} ErrorResponse "LLM hard budget exceeded"
// @Failure 500 {object} ErrorResponse
// @Failure 503 {object} ErrorResponse "LLM provider or budget ledger unavailable"
// @Router /admin/rules/predict-intent [post]
func (h *Handler) PredictIntent(w http.ResponseWriter, r *http.Request) {
	var req PredictIntentRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "BAD_REQUEST", "invalid request body")
		return
	}
	if req.Recording == nil {
		writeError(w, http.StatusBadRequest, "BAD_REQUEST", "recording is required")
		return
	}
	// Inline recordings arrive in the extension's compressed form (identical
	// snapshots as references, near-identical as deltas). Expand before the
	// predictor resolves element indexes against snapshot selector maps.
	if err := platformrecording.ExpandSnapshotReferences(req.Recording); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_RECORDING", err.Error())
		return
	}

	ctx := withServerOwnedDispatch(r.Context(), budget.OperationIntent)
	result, err := h.intentPredictor.Predict(ctx, req.Recording)
	if err != nil {
		h.logger.Error("predict intent failed", zap.Error(err))
		if writeLLMDispatchError(w, err) {
			return
		}
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "failed to predict intent")
		return
	}

	h.auditLog(r.Context(), "predict_intent", "recording", "", map[string]any{
		"model":    result.Model,
		"cacheHit": result.CacheHit,
		"count":    len(result.Candidates),
	})

	resp := PredictIntentResponse{
		Candidates:     toIntentCandidates(result.Candidates),
		FallbackIntent: toIntentCandidate(result.FallbackIntent),
		Model:          result.Model,
		CacheHit:       result.CacheHit,
	}
	writeJSON(w, http.StatusOK, resp)
}

func toIntentCandidates(candidates []intent.Candidate) []IntentCandidate {
	out := make([]IntentCandidate, 0, len(candidates))
	for _, c := range candidates {
		out = append(out, toIntentCandidate(c))
	}
	return out
}

func toIntentCandidate(c intent.Candidate) IntentCandidate {
	return IntentCandidate{
		ID:                 c.ID,
		Label:              c.Label,
		Description:        c.Description,
		Confidence:         c.Confidence,
		SuggestedVariables: c.SuggestedVariables,
	}
}
